---
- hosts: masters
  tasks:
    - name: '## Masters - Yum Packages ##'
      yum:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - vim
    
- hosts: datanodes
  tasks:
    - name: '## DataNodes - Yum Packages ##'
      yum:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - vim

    - name: "## Download / Extract Wordpress ##"
      unarchive:
        src: https://www-us.apache.org/dist/hadoop/core/stable/hadoop-3.2.0.tar.gz
        dest: /opt/hadoop
        remote_src: yes
        creates: /opt/hadoop
      become: yes